// frontend/src/components/LoginWithSpotify.svelte
<button class="button is-primary" on:click={login}>
    Log in with Spotify
</button>

<script>
import {push, pop, replace} from 'svelte-spa-router'
import { onMount } from 'svelte';

let redirectURI = "";

let state = "";

onMount( async () => {
    const resp = await fetch("http://localhost:5000/api/getCallbackURL", 
	{ credentials: 'include' }
    );
    if(resp.ok) {
	const data = await resp.json();
	redirectURI = data.data.url;
	state = data.data.state;
    }
});

function login() {
    // Save state in a cookie
    document.cookie = "spotifyState=" + state;
    // Redirect to URI
    window.location.href = redirectURI;
}

</script>

// frontend/src/components/LoginWithSpotify.vue
<template>
    <button class="button is-primary" @click="login()">
	Log in with Spotify
    </button>
</template>

<script lang="ts">
import { Component, Vue } from "vue-property-decorator";

import axios from "axios";

@Component
export default class LoginWithSpotify extends Vue {
    public redirectURI = "";
    public state = "";

    public mounted() {
	const component = this;
	axios.get("http://localhost:5000/api/getCallbackURL").then((response: any) => {
	    component.redirectURI = response.data.data.url;
	    component.state = response.data.data.state;
	}).catch((error: any) => {
	    // Dunno what to do here
	});
    }
    public login() {
	// Save state in a cookie
	document.cookie = "spotifyState=" + this.state;
	window.location.href = this.redirectURI;
    }
}
</script>
