// frontend/src/App.vue
<template>
  <div id="app">
    <nav class="navbar is-primary" role="navigation">
      <div class="navbar-brand">
	  <div class="navbar-item">
	      <img src="logo-white.png" height="40" >
	      <span class="logo-text">
	      Melodic
	      </span>
	  </div>
      </div>
      <div class="navbar-start">
	<router-link class="navbar-item" to="/">Home</router-link>
	<router-link class="navbar-item" to="/about">About</router-link>
      </div>
      <div class="navbar-end">
	  <a class="navbar-item" href="#">Our Socials!</a>
      </div>
    </nav>
    <div class="container" id="main-container">
	<template v-for="(message, index) in store.messages">
	    <div class="notification" 
		v-bind:class="message.color">
		<button class="delete"
		    @click="store.removeMessageByIndex(index)">
		</button>
		{{message.text}}
	    </div>
	</template>
	<router-view/>
    </div>
  </div>
</template>

<script lang="ts">
import { store } from "./store";
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class App extends Vue {
    // Attach global store so that it becomes reactive
    // This is used to display messages
    store = store
}
</script>

<style>
#main-container {
    margin-top: 15px;
}
.logo-text {
    margin-left: 5px;
    font-family: "Georgia", Serif;
    font-weight: bold;
    font-size: 1.5rem;
}
</style>

// frontend/src/App.svelte
<!-- Navigation links, using the "link" action -->
<!-- Also, use the "active" action to add the "active" CSS class when the URL matches -->
<nav class="navbar is-primary" role="navigation">
  <div class="navbar-brand">
      <div class="navbar-item">
	  <img src="logo-white.png" alt="Melodic Logo" height="40" >
	  <span class="logo-text">
	  Melodic
	  </span>
      </div>
  </div>
  <div class="navbar-start">
    <a class="navbar-item" href="/" use:link use:active>Home</a>
    <a class="navbar-item" href="/about" use:link use:active>About</a>
  </div>
  <div class="navbar-end">
      <a class="navbar-item" href="/" >Our Socials!</a>
  </div>
</nav>
<div class="container" id="main-container">
	<div class="notification">
	    <button class="delete" >
	    </button>
	    This is a notification
	</div>
    <!-- Show the router -->
    <Router {routes} />
</div>


<script>
// Import the router component
import Router from 'svelte-spa-router'
// Import the "link" action and the methods to control history programmatically from the same module, as well as the location store
import { link, replace } from 'svelte-spa-router'
import active from 'svelte-spa-router/active'
// Import the list of routes
import routes from './routes'
</script>

<style>
#main-container {
    margin-top: 15px;
}
.logo-text {
    margin-left: 5px;
    font-family: "Georgia", Serif;
    font-weight: bold;
    font-size: 1.5rem;
}
</style>
